# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelCli < Formula
  desc "OpenTelemetry command-line tool for sending events from shell scripts & similar environments"
  homepage "https://github.com/tobert/otel-cli"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobert/otel-cli/releases/download/v0.5.0/otel-cli_0.5.0_darwin_amd64.tar.gz"
      sha256 "6d32e456b87d66de6da7f67e4a36e760076f1e4bb803ca7f3725eb66db435dd4"

      def install
        bin.install "otel-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobert/otel-cli/releases/download/v0.5.0/otel-cli_0.5.0_darwin_arm64.tar.gz"
      sha256 "43c82871f10617486e6b49bbbf36822aaf146478647796982136a9bf3b7f4334"

      def install
        bin.install "otel-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tobert/otel-cli/releases/download/v0.5.0/otel-cli_0.5.0_linux_amd64.tar.gz"
        sha256 "57659e2c789e3ee73dfaeab4638cffdeb169c10550fecea3e4ea407af9459dce"

        def install
          bin.install "otel-cli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tobert/otel-cli/releases/download/v0.5.0/otel-cli_0.5.0_linux_arm64.tar.gz"
        sha256 "2a8078ba4d9251b60556ed532f3e2190fe3fc32cdfe5d0dcbaf6e1bf921e1420"

        def install
          bin.install "otel-cli"
        end
      end
    end
  end
end
